var Web3 = require('web3');

var web3 = new Web3();

web3.setProvider(new web3.providers.HttpProvider('http://127.0.0.1:8588'));

// set default account (coins/tokens are sent from this address);
web3.eth.defaultAccount = web3.eth.coinbase; //eth.coinbase is a shortcut to the first account generated by gubiq.

//define the contract (dont change this, i will provide new abi information for the live qwark contract)
var abi = [
  {
    "constant": true,
    "inputs": [],
    "name": "name",
    "outputs": [
      {
        "name": "",
        "type": "string",
        "value": "Qwark"
      }
    ],
    "payable": false,
    "type": "function"
  },
  {
    "constant": false,
    "inputs": [
      {
        "name": "_spender",
        "type": "address"
      },
      {
        "name": "_value",
        "type": "uint256"
      }
    ],
    "name": "approve",
    "outputs": [
      {
        "name": "success",
        "type": "bool"
      }
    ],
    "payable": false,
    "type": "function"
  },
  {
    "constant": true,
    "inputs": [],
    "name": "totalSupply",
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "value": "25037757589618036"
      }
    ],
    "payable": false,
    "type": "function"
  },
  {
    "constant": false,
    "inputs": [
      {
        "name": "_from",
        "type": "address"
      },
      {
        "name": "_to",
        "type": "address"
      },
      {
        "name": "_value",
        "type": "uint256"
      }
    ],
    "name": "transferFrom",
    "outputs": [
      {
        "name": "success",
        "type": "bool"
      }
    ],
    "payable": false,
    "type": "function"
  },
  {
    "constant": true,
    "inputs": [],
    "name": "decimals",
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "value": "8"
      }
    ],
    "payable": false,
    "type": "function"
  },
  {
    "constant": true,
    "inputs": [],
    "name": "standard",
    "outputs": [
      {
        "name": "",
        "type": "string",
        "value": "Qwark 0.1"
      }
    ],
    "payable": false,
    "type": "function"
  },
  {
    "constant": true,
    "inputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "name": "balanceOf",
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "value": "0"
      }
    ],
    "payable": false,
    "type": "function"
  },
  {
    "constant": true,
    "inputs": [],
    "name": "symbol",
    "outputs": [
      {
        "name": "",
        "type": "string",
        "value": "QWARK"
      }
    ],
    "payable": false,
    "type": "function"
  },
  {
    "constant": false,
    "inputs": [
      {
        "name": "_to",
        "type": "address"
      },
      {
        "name": "_value",
        "type": "uint256"
      }
    ],
    "name": "transfer",
    "outputs": [],
    "payable": false,
    "type": "function"
  },
  {
    "constant": false,
    "inputs": [
      {
        "name": "_spender",
        "type": "address"
      },
      {
        "name": "_value",
        "type": "uint256"
      },
      {
        "name": "_extraData",
        "type": "bytes"
      }
    ],
    "name": "approveAndCall",
    "outputs": [
      {
        "name": "success",
        "type": "bool"
      }
    ],
    "payable": false,
    "type": "function"
  },
  {
    "constant": true,
    "inputs": [
      {
        "name": "",
        "type": "address"
      },
      {
        "name": "",
        "type": "address"
      }
    ],
    "name": "allowance",
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "value": "0"
      }
    ],
    "payable": false,
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "initialSupply",
        "type": "uint256",
        "index": 0,
        "typeShort": "uint",
        "bits": "256",
        "displayName": "initial Supply",
        "template": "elements_input_uint",
        "value": "25037757589618036"
      },
      {
        "name": "tokenName",
        "type": "string",
        "index": 1,
        "typeShort": "string",
        "bits": "",
        "displayName": "token Name",
        "template": "elements_input_string",
        "value": "Qwark"
      },
      {
        "name": "decimalUnits",
        "type": "uint8",
        "index": 2,
        "typeShort": "uint",
        "bits": "8",
        "displayName": "decimal Units",
        "template": "elements_input_uint",
        "value": "8"
      },
      {
        "name": "tokenSymbol",
        "type": "string",
        "index": 3,
        "typeShort": "string",
        "bits": "",
        "displayName": "token Symbol",
        "template": "elements_input_string",
        "value": "QWARK"
      }
    ],
    "payable": false,
    "type": "constructor"
  },
  {
    "payable": false,
    "type": "fallback"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "from",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "to",
        "type": "address"
      },
      {
        "indexed": false,
        "name": "value",
        "type": "uint256"
      }
    ],
    "name": "Transfer",
    "type": "event"
  }
];

//declare the contract/token object
var qwark =  web3.eth.contract(abi).at("0x4b4899a10f3e507db207b0ee2426029efa168a67");

/* // test contract is loaded correctly;
if (qwark.address) {
  console.log(qwark.address);
} else {
  console.log('err');
}
*/

// address to send to
var toAddress = 'enter your collection/exchange address here';
// amount to send in smallest units (satoshis), e.g 1.0 qwark = 100000000 satoshi
var amount = 300000000000000; // 1 qwark

qwark.transfer(toAddress, amount, function(err, txid){
  if (err) {
    console.log(err);
  } else {
    console.log('txid:' + txid);
  }
});
